### ISSUE TITLE
reshape should be made dependent on resample

### ISSUE THREAD

**Issue by cazaudo** [Project-ODE/OSmOSE_package#32]
currently there is a bug when you do resample + reshape because jobs run simultaneously , and if i understand properly the parameters of reshape it reshapes the resampled wav moved on the output directory , so reshape job should be made dependent on resample job

Parameters : Namespace(input_files='/home/datawork-osmose/dataset/test_sample_DC/data/audio/10_2150', chunk_size=10, output_dir='/home/datawork-osmose/dataset/test_sample_DC/data/audio/10_2150', batch_ind_min=0, batch_ind_max=39, offset_beginning=0, offset_end=0, max_delta_interval=5, verbose=True, overwrite=True, force=True, last_file_behavior='pad')

**Comment by Rumengol** [comment]
It is the case already, but there was an oversight for when the data normalization step is skipped. The referenced commit fixes the issue.
